builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - binaries:
      - ghtop
    image_templates:
      - 'patrickhoefler/ghtop:latest'
      - 'patrickhoefler/ghtop:{{ .Major }}'
      - 'patrickhoefler/ghtop:{{ .Major }}.{{ .Minor }}'
      - 'patrickhoefler/ghtop:{{ .Major }}.{{ .Minor }}.{{ .Patch }}'

brews:
  - tap:
      owner: patrickhoefler
      name: homebrew-ghtop

    homepage: https://github.com/patrickhoefler/ghtop
    description: 'Get information about the most starred GitHub repos'
